[package]
name = "xiv-dl-cache"
description = "FFXIV Downloader via CLUT files"
authors = ["Asriel Camora <asriel@camora.dev>"]
license = "GPL-3.0"
repository = "https://github.com/WorkingRobot/ffxiv-downloader"
edition = "2024"

[lib]
name = "xiv_cache"

[features]
prometheus = ["dep:prometheus", "dep:mixtrics"]

[dependencies]
xiv-dl-core = { path = "../core" }
shadow-rs = { version = "1.2", default-features = false }
tokio = { version = "1.47", features = ["full"] }
reqwest = { version = "0.12", features = ["stream", "json"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
bytes = "1.0"
futures = "0.3"
url = "2.5"
either = "1.15"
foyer = { version = "0.19", features = ["serde"] }
moka = { version = "0.12", features = ["future"] }
tokio-util = "0.7"
itertools = "0.14"
prometheus = { version = "0.14", optional = true }
mixtrics = { version = "0.2", features = ["prometheus"], optional = true }

[build-dependencies]
shadow-rs = "1.2"
