[package]
name = "xiv-dl-core"
description = "FFXIV Downloader via CLUT files"
authors = ["Asriel Camora <asriel@camora.dev>"]
license = "GPL-3.0"
repository = "https://github.com/WorkingRobot/ffxiv-downloader"
edition = "2024"

[lib]
name = "xiv_core"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
reqwest = { version = "0.12", features = ["stream", "json"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
bytes = "1.0"
futures = "0.3"
binrw = "0.15"
tokio-util = "0.7"
flate2 = "1.0"
brotli = "8.0"
multer = { version = "3.1", features = ["log", "tokio-io"] }
http-content-range = "0.2"
graphql_client = "0.14"
