[package]
name = "xiv-dl-core"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "xiv_core"

[dependencies]
shadow-rs = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
binrw = "0.15"
tokio-util = "0.7"
flate2 = "1.0"
brotli = "8.0"
multer = { version = "3.1", features = ["log", "tokio-io"] }
http-content-range = "0.2"
graphql_client = "0.14"

[build-dependencies]
shadow-rs = { workspace = true, default-features = true }
